name: Dependabot Auto-merge

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    dependabot:
        runs-on: ubuntu-latest
        if: github.actor == 'dependabot[bot]'

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup pnpm
          uses: pnpm/action-setup@v2
          with:
            version: 10

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20.x'
            cache: 'pnpm'

        - name: Install dependencies
          run: pnpm install --frozen-lockfile

        - name: Run test
          run: pnpm test

        - name: Build package
          run: pnpm build

        - name: Auto-merge minor updates
          if: contains(github.event.pull_request.title, 'bump') && !contains(github.event.pull_request.title, 'major')
          run: |
            echo "Auto-merging dependency update..."
            gh pr review --approve "$PR_URL"
            gh pr merge --auto --merge "$PR_URL"
          env:
            PR_URL: ${{ github.event.pull_request.html_url }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}